name: Deploy

on:
  push:
    branches: [ main ]
    paths:
      - 'Sources/whitelabel/Config.swift'

jobs:
  build:

    runs-on: [self-hosted, raspi64]

    steps:
    - uses: actions/checkout@v2
    # - uses: fwal/setup-swift@v1
    - name: Generate artefacts
      run: swift run
    # - name: Upload files to S3
    #   run: ./.build/debug/whitelabel
