//
//  UIColor+SLAdditions.swift
//
//  Generated by Zeplin on 1/13/17.
//  Copyright (c) 2017 __MyCompanyName__. All rights reserved. 
//

import UIKit

extension UIColor {
	class var slBluegrey: UIColor {
		return UIColor(red: 130.0 / 255.0, green: 156.0 / 255.0, blue: 178.0 / 255.0, alpha: 1.0)
	}

	class var slLightBlueGrey: UIColor {
		return UIColor(red: 160.0 / 255.0, green: 200.0 / 255.0, blue: 224.0 / 255.0, alpha: 1.0)
	}

    class var slWarmGrey: UIColor {
        return UIColor(red: 156.0 / 255.0, green: 151.0 / 255.0, blue: 151.0 / 255.0, alpha: 1.0)
    }
	class var slDenim: UIColor {
		return UIColor(red: 60.0 / 255.0, green: 83.0 / 255.0, blue: 119.0 / 255.0, alpha: 1.0)
	}

	class var slCoolGrey: UIColor {
		return UIColor(red: 157.0 / 255.0, green: 161.0 / 255.0, blue: 167.0 / 255.0, alpha: 1.0)
	}

	class var slWarmGreyTwo: UIColor { 
		return UIColor(white: 140.0 / 255.0, alpha: 1.0)
	}

	class var slPinkishGrey: UIColor { 
		return UIColor(white: 188.0 / 255.0, alpha: 1.0)
	}
    
    class var slRobinsEgg: UIColor {
        return UIColor(red: 87.0 / 255.0, green: 216.0 / 255.0, blue: 255.0 / 255.0, alpha: 1.0)
    }
    
    class var slCoolGreyTwo: UIColor {
        return UIColor(red: 161.0 / 255.0, green: 165.0 / 255.0, blue: 171.0 / 255.0, alpha: 1.0)
    }
    
    class var slPinkishGreyTwo: UIColor {
        return UIColor(white: 194.0 / 255.0, alpha: 1.0)
    }
    
    class var slWhiteTwo: UIColor {
        return UIColor(white: 210.0 / 255.0, alpha: 1.0)
    }
    
    class var slWarmGreyThree: UIColor {
        return UIColor(white: 144.0 / 255.0, alpha: 1.0)
    }
    
    class var slPinkishGreyThree: UIColor {
        return UIColor(red: 188.0 / 255.0, green: 187.0 / 255.0, blue: 187.0 / 255.0, alpha: 1.0)
    }
    
    class var slNavy: UIColor {
        return UIColor(red: 5.0 / 255.0, green: 28.0 / 255.0, blue: 63.0 / 255.0, alpha: 1.0)
    }
    
    class var slPaleGrey: UIColor {
        return UIColor(red: 236.0 / 255.0, green: 239.0 / 255.0, blue: 244.0 / 255.0, alpha: 1.0)
    }
    
    class var slSteel: UIColor {
        return UIColor(red: 128.0 / 255.0, green: 132.0 / 255.0, blue: 140.0 / 255.0, alpha: 1.0)
    }
    
    class var slWhite: UIColor {
        return UIColor(red: 240.0 / 255.0, green: 239.0 / 255.0, blue: 239.0 / 255.0, alpha: 1.0)
    }
    
    class var slSoftBlue: UIColor {
        return UIColor(red: 102.0 / 255.0, green: 177.0 / 255.0, blue: 227.0 / 255.0, alpha: 1.0)
    }
    
    class var slSlateGrey: UIColor {
        return UIColor(red: 76.0 / 255.0, green: 79.0 / 255.0, blue: 97.0 / 255.0, alpha: 1.0)
    }
    
    class var slLightBlueGreyTwo: UIColor {
        return UIColor(red: 180.0 / 255.0, green: 212.0 / 255.0, blue: 231.0 / 255.0, alpha: 1.0)
    }
}
