
name: TestFlight

on:
  push:
    branches: [ main ]

jobs:
  testflight:
    runs-on: [self-hosted, deploy-ios]
    steps:
      - uses: actions/checkout@v2
      - name: Update bundle
        run: bundle update
      - name: Build and Deploy to TestFlight
        env:
          APP_STORE_EMAIL: ${{ secrets.APP_STORE_EMAIL }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
        run: LANG=en_US.UTF-8 bundle exec fastlane release
