//
//  UIColor+OM.swift
//
//  Generated by Zeplin on 12/24/16.
//  Copyright (c) 2016 __MyCompanyName__. All rights reserved. 
//

import UIKit

extension UIColor {
	class var lsSteel: UIColor {
		return UIColor(red: 128.0 / 255.0, green: 132.0 / 255.0, blue: 140.0 / 255.0, alpha: 1.0)
	}

	class var lsCoolGrey: UIColor {
		return UIColor(red: 172.0 / 255.0, green: 177.0 / 255.0, blue: 187.0 / 255.0, alpha: 1.0)
	}

	class var lsDeepSeaBlue: UIColor {
		return UIColor(red: 0.0, green: 100.0 / 255.0, blue: 124.0 / 255.0, alpha: 1.0)
	}

	class var lsTurquoiseBlue: UIColor {
		return UIColor(red: 0.0, green: 170.0 / 255.0, blue: 209.0 / 255.0, alpha: 1.0)
	}

    class var lsTurquoiseBlue2: UIColor {
        return UIColor(red: 87.0 / 255.0, green: 216.0 / 255.0, blue: 255.0 / 255.0, alpha: 1.0)
    }
    
	class var lsSilver: UIColor {
		return UIColor(red: 222.0 / 255.0, green: 224.0 / 255.0, blue: 229.0 / 255.0, alpha: 1.0)
	}

    class var lsWarmGrey: UIColor {
        return UIColor(white: 129.0 / 255.0, alpha: 1.0)
    }
    
    class var lsWhite: UIColor {
        return UIColor(white: 249.0 / 255.0, alpha: 1.0)
    }
    
    class var lsBlack27: UIColor {
        return UIColor(white: 0.0, alpha: 0.27)
    }
    
    class var lsWarmGreyThree: UIColor {
        return UIColor(white: 134.0 / 255.0, alpha: 1.0)
    }
    
    class var lsPaleGrey: UIColor {
        return UIColor(red: 244.0 / 255.0, green: 245.0 / 255.0, blue: 246.0 / 255.0, alpha: 1.0)
    }
    
    class var lsWarmGreyFour: UIColor {
        return UIColor(white: 129.0 / 255.0, alpha: 1.0)
    }
    
    class var lsSilverTwo: UIColor {
        return UIColor(red: 208.0 / 255.0, green: 211.0 / 255.0, blue: 216.0 / 255.0, alpha: 1.0)
    }
    
    class var lsSilverThree: UIColor {
        return UIColor(red: 214.0 / 255.0, green: 217.0 / 255.0, blue: 224.0 / 255.0, alpha: 1.0)
    }
    
    class var lsCoolGreyTwo: UIColor {
        return UIColor(red: 167.0 / 255.0, green: 168.0 / 255.0, blue: 171.0 / 255.0, alpha: 1.0)
    }
    
    class var lsGreyish: UIColor {
        return UIColor(white: 181.0 / 255.0, alpha: 1.0)
    }
    
    class var lsSteelTwo: UIColor {
        return UIColor(red: 133.0 / 255.0, green: 133.0 / 255.0, blue: 134.0 / 255.0, alpha: 1.0)
    }
    
    class var lsRobinsEgg10: UIColor {
        return UIColor(red: 87.0 / 255.0, green: 216.0 / 255.0, blue: 255.0 / 255.0, alpha: 0.1)
    }
    
    class var lsRobinsEgg: UIColor {
        return UIColor(red: 87.0 / 255.0, green: 216.0 / 255.0, blue: 255.0 / 255.0, alpha: 1.0)
    }
    
    class var disabledActiveButtonBackgground: UIColor {
        return UIColor(white: 0.9, alpha: 1)
    }
}
