# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Ellipse' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Ellipse
  pod 'Oval', :git => 'git@github.com:velolabs/oval_ios.git', :branch => 'develop'
#  pod 'Oval', :path => '../oval_ios/'
  pod 'LattisSDK', :git => 'git@github.com:velolabs/lattis_sdk_ios.git', :branch => 'develop'
#  pod 'LattisSDK', :path => '../../Lattis SDK Demo/'
  pod 'Pageboy'
  pod 'Cartography'
  pod 'Localize-Swift'
  pod 'TPKeyboardAvoiding'
  pod 'PhoneNumberKit'
  pod 'LGSideMenuController'
  pod 'Fabric'
  pod 'Crashlytics', '~>  3.9'
  pod 'SwipeCellKit'
  pod 'UICircularProgressRing', :git => 'git@github.com:darecki/UICircularProgressRing.git', :branch => 'swift_5'
  pod 'ImagePicker'
  pod 'FacebookLogin'
  pod 'Mapbox-iOS-SDK', '3.6'
  pod 'JTMaterialSpinner', :git => 'git@github.com:kabanishe23/JTMaterialSpinner.git'
  pod 'KeychainSwift'
  pod 'EasyTipView'#, '~> 1.0.2'
  pod 'Firebase/Core'
  pod 'Atributika'
  pod 'Device', '~> 3.1.2'
end

swift_3_frameworks = ['EasyTipView']
swift_4_frameworks = ['ImagePicker']

post_install do |installer|
    installer.pods_project.targets.each do |target|
#        if swift_3_frameworks.include? target.name
#            target.build_configurations.each do |config|
#                config.build_settings['SWIFT_VERSION'] = '3.2'
#            end
#        end
        if swift_4_frameworks.include? target.name
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '4'
            end
        end
    end
end

