version: 0.0
os: linux
files:
  - source: /
    destination: /opt/jobs
permission:
  - object: /opt/jobs
    owner: gpstracking
    group: gpstracking
    type:
      - directory
      - file

hooks:
  BeforeInstall:
    - location: codeploy/stop_app.sh
      runas: gpstracking
  AfterInstall:
    - location: codeploy/download_app.sh
      runas: root
  ApplicationStart:
    - location: codeploy/start_app.sh
      timeout: 300
      runas: gpstracking
