#ifndef TWI_MASTER_CONFIG
#define TWI_MASTER_CONFIG

#include "skylock_gpio.h"

#define TWI1_MASTER_CONFIG_CLOCK_PIN_NUMBER (I2C_SCL)
#define TWI1_MASTER_CONFIG_DATA_PIN_NUMBER (I2C_SDA)

#define TWI0_MASTER_CONFIG_CLOCK_PIN_NUMBER (ACC_I2C_SCL)
#define TWI0_MASTER_CONFIG_DATA_PIN_NUMBER (ACC_I2C_SDA)

// goddamn this shit stinks.  See nordic twi_master.h for the origin of this bullshit.

#define TWI1_SCL_HIGH()   do { NRF_GPIO->OUTSET = (1UL << TWI1_MASTER_CONFIG_CLOCK_PIN_NUMBER); } while(0)
#define TWI1_SCL_LOW()    do { NRF_GPIO->OUTCLR = (1UL << TWI1_MASTER_CONFIG_CLOCK_PIN_NUMBER); } while(0)
#define TWI1_SDA_HIGH()   do { NRF_GPIO->OUTSET = (1UL << TWI1_MASTER_CONFIG_DATA_PIN_NUMBER);  } while(0)
#define TWI1_SDA_LOW()    do { NRF_GPIO->OUTCLR = (1UL << TWI1_MASTER_CONFIG_DATA_PIN_NUMBER);  } while(0)
#define TWI1_SDA_INPUT()  do { NRF_GPIO->DIRCLR = (1UL << TWI1_MASTER_CONFIG_DATA_PIN_NUMBER);  } while(0)
#define TWI1_SDA_OUTPUT() do { NRF_GPIO->DIRSET = (1UL << TWI1_MASTER_CONFIG_DATA_PIN_NUMBER);  } while(0)
#define TWI1_SCL_OUTPUT() do { NRF_GPIO->DIRSET = (1UL << TWI1_MASTER_CONFIG_CLOCK_PIN_NUMBER); } while(0)
#define TWI1_SDA_READ() ((NRF_GPIO->IN >> TWI1_MASTER_CONFIG_DATA_PIN_NUMBER) & 0x1UL)
#define TWI1_SCL_READ() ((NRF_GPIO->IN >> TWI1_MASTER_CONFIG_CLOCK_PIN_NUMBER) & 0x1UL)

#define TWI0_SCL_HIGH()   do { NRF_GPIO->OUTSET = (1UL << TWI0_MASTER_CONFIG_CLOCK_PIN_NUMBER); } while(0)
#define TWI0_SCL_LOW()    do { NRF_GPIO->OUTCLR = (1UL << TWI0_MASTER_CONFIG_CLOCK_PIN_NUMBER); } while(0)
#define TWI0_SDA_HIGH()   do { NRF_GPIO->OUTSET = (1UL << TWI0_MASTER_CONFIG_DATA_PIN_NUMBER);  } while(0)
#define TWI0_SDA_LOW()    do { NRF_GPIO->OUTCLR = (1UL << TWI0_MASTER_CONFIG_DATA_PIN_NUMBER);  } while(0)
#define TWI0_SDA_INPUT()  do { NRF_GPIO->DIRCLR = (1UL << TWI0_MASTER_CONFIG_DATA_PIN_NUMBER);  } while(0)
#define TWI0_SDA_OUTPUT() do { NRF_GPIO->DIRSET = (1UL << TWI0_MASTER_CONFIG_DATA_PIN_NUMBER);  } while(0)
#define TWI0_SCL_OUTPUT() do { NRF_GPIO->DIRSET = (1UL << TWI0_MASTER_CONFIG_CLOCK_PIN_NUMBER); } while(0)
#define TWI0_SDA_READ() ((NRF_GPIO->IN >> TWI0_MASTER_CONFIG_DATA_PIN_NUMBER) & 0x1UL)
#define TWI0_SCL_READ() ((NRF_GPIO->IN >> TWI0_MASTER_CONFIG_CLOCK_PIN_NUMBER) & 0x1UL)

#define TWI_DELAY() nrf_delay_us(4)


#endif
