//
//  UIFont+LSAdditions.swift
//
//  Generated by Zeplin on 2/13/17.
//  Copyright (c) 2017 __MyCompanyName__. All rights reserved. 
//

import UIKit

enum FontType: String {
    case circularBook = "CircularStd-Book"
    case circularBold = "CircularStd-Bold"
    case circularMedium = "CircularStd-Medium"
}

extension UIFont {
	class func lsTitleStyleFont() -> UIFont? {
		return UIFont(name: "CircularStd-Book", size: 14.0)
	}
    
    convenience init?(_ type: FontType, size: CGFloat) {
        self.init(name: type.rawValue, size: size)
    }
}
