fastlane_version "2.10.0"

default_platform :ios

platform :ios do
  #
  # Learn more here: https://github.com/fastlane/setups/blob/master/samples-ios/distribute-beta-build.md 🚀
  #
  lane :beta do |values|
    # Fabric generated this lane for deployment to Crashlytics Beta
    # set 'export_method' to 'ad-hoc' if your Crashlytics Beta distribution uses ad-hoc provisioning
    gym(scheme: 'Ellipse Dev', export_method: 'ad-hoc')

    emails = values[:test_email] ? values[:test_email] : ['ravil@lattis.io'] # You can list more emails here
    groups = values[:test_email] ? nil : ['lattis-internal'] # You can define groups on the web and reference them here

    crashlytics(api_token: '2a7c173f04d3a790e6717f79ae91223089986b40',
             build_secret: 'b5d39bb00fdb0bfc027b4671fadb82b50c33ac2083b3bf4f08d34585271a4b1f',
                   emails: emails,
                   groups: groups,
               notes_path: 'BETA.md',
            notifications: true) # Should this distribution notify your testers via email?

    # for all available options run `fastlane action crashlytics`

    # You can notify your team in chat that a beta build has been uploaded
    slack(
       slack_url: "https://hooks.slack.com/services/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",
       channel: "ellipse",
       message: "Successfully uploaded a beta release - see it at https://betas.to/qqaw5dvx"
     )
  end
end
