version: 0.0
os: linux
files:
  - source: /
    destination: /opt/lattis-iot-apis-nodejs
permission:
  - object: /opt/lattis-iot-apis-nodejs
    owner: ubuntu
    group: ubuntu
    type:
      - directory
      - file

hooks:
  BeforeInstall:
    - location: codeploy/stop_app.sh
      runas: ubuntu
  AfterInstall:
    - location: codeploy/download_app.sh
      runas: root
  ApplicationStart:
    - location: codeploy/start_app.sh
      timeout: 300
      runas: ubuntu
