version: 0.0
os: linux
files:
  - source: /
    destination: /opt/oval
permission:
  - object: /opt/oval
    owner: oval
    group: oval
    type:
      - directory
      - file

hooks:
  BeforeInstall:
    - location: codeploy/stop_app.sh
      runas: oval
  AfterInstall:
    - location: codeploy/download_app.sh
      runas: root
  ApplicationStart:
    - location: codeploy/start_app.sh
      timeout: 300
      runas: oval
