version: 0.0
os: linux
files:
  - source: /
    destination: /opt/circle/
permission:
  - object: /opt/circle
    pattern: "**"
    owner: circle
    group: circle
    type:
      - file
      - directory
hooks:
  BeforeInstall:
    - location: codeploy/stop_app.sh
      runas: circle
  AfterInstall:
    - location: codeploy/download_app.sh
      runas: root
  ApplicationStart:
    - location: codeploy/start_app.sh
      timeout: 300
      runas: circle
